"""
Django settings for auditoria_aylupita project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import sys
from pathlib import Path

import dj_database_url
import environ

# runtime_paths vive en la raíz del proyecto (junto a manage.py), no dentro
# del paquete auditoria_aylupita — hace falta en sys.path explícitamente
# porque, empaquetado con PyInstaller, el mecanismo normal de import de
# Django (vía manage.py) no interviene.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from runtime_paths import carpeta_codigo, carpeta_escribible  # noqa: E402

# BASE_DIR: carpeta de solo lectura con el código, templates y estáticos.
# Sin empaquetar es la raíz del proyecto de siempre; empaquetada con
# PyInstaller es la carpeta del bundle (sys._MEIPASS) — nunca la carpeta
# real donde vive el .exe, que puede no ser escribible.
BASE_DIR = carpeta_codigo()

# BASE_DIR_ESCRIBIBLE: carpeta donde SÍ se puede crear o modificar archivos
# (base de datos, media). Sin empaquetar es la misma que BASE_DIR;
# empaquetada, es la carpeta donde vive el .exe real — la única que el
# usuario controla y que persiste entre ejecuciones.
BASE_DIR_ESCRIBIBLE = carpeta_escribible()

# .env vive junto al .exe real (o en la raíz del proyecto en desarrollo,
# donde BASE_DIR_ESCRIBIBLE == BASE_DIR) — nunca dentro del bundle de solo
# lectura, y nunca se sube a git (confirmar en .gitignore). Si no existe
# (ej. una máquina sin Postgres configurado todavía), read_env() no hace
# nada y simplemente se usan las variables de entorno del sistema, si las
# hay — de ahí cae al fallback de SQLite más abajo.
env = environ.Env()
environ.Env.read_env(str(BASE_DIR_ESCRIBIBLE / ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1s^p=s9_-%a%6il%+%_3e_gjtd1_j_+06ebyqs^ou7pan&#_!i'

# SECURITY WARNING: don't run with debug turned on in production!
# Se lee de .env (prompt 22) — False por defecto si no está definida, así
# que una máquina sin .env configurado (ej. el .exe entregado al auditor)
# nunca corre con DEBUG=True por accidente. Actívalo explícitamente solo
# en tu propio .env de desarrollo local: DEBUG=True
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'inventario',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'auditoria_aylupita.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'inventario.context_processors.rol',
            ],
        },
    },
]

WSGI_APPLICATION = 'auditoria_aylupita.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Postgres en la nube (Neon) si hay DATABASE_URL en el entorno/.env;
# si no, SQLite local como respaldo de desarrollo (prompt 18) — así se
# puede seguir probando sin nube si hace falta, sin tocar código.
#
# manage.py migrate usa DIRECT_DATABASE_URL en vez de DATABASE_URL cuando
# está definida: Neon recomienda la conexión directa (sin el pooler
# pgbouncer) específicamente para migraciones, mientras que la app en uso
# normal sí debe pasar por el pooler. Nota: app_desktop.py también corre
# "migrate" en cada arranque (self-healing en un equipo nuevo, prompt 13b)
# pero NO pasa por manage.py — ese arranque usa DATABASE_URL (el pooler)
# igual que el resto de la app. En la práctica un migrate sin nada
# pendiente es una operación liviana que no debería toparse con las
# limitaciones del pooler, pero si algún día da problemas ahí, es el
# lugar a revisar.
_es_comando_migrate = len(sys.argv) > 1 and sys.argv[1] == "migrate"

_database_url = env("DATABASE_URL", default=None)
_direct_database_url = env("DIRECT_DATABASE_URL", default=None)

if _database_url:
    _url_para_conectar = _direct_database_url if (_es_comando_migrate and _direct_database_url) else _database_url
    DATABASES = {
        "default": dj_database_url.parse(_url_para_conectar, conn_max_age=60, ssl_require=True)
    }
    # Detecta una conexión persistente muerta (ej. el cómputo serverless de
    # Neon se suspendió por inactividad) y la reabre en vez de fallar la
    # siguiente request — dj_database_url.parse() no siempre expone este
    # parámetro según la versión instalada, se fija aparte por seguridad.
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR_ESCRIBIBLE / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-ni'  # Django no incluye es-gt; es-ni usa la misma convención numérica (punto decimal, coma de miles) que Guatemala

TIME_ZONE = 'America/Guatemala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media: no hay ningún FileField/ImageField en el catálogo actual, pero se
# deja definido (relativo a la carpeta escribible, no al bundle) para que
# cualquier subida de archivo que se agregue a futuro caiga en el lugar
# correcto sin tener que recordar este mismo problema de rutas.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR_ESCRIBIBLE / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/6.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# django-crispy-forms
CRISPY_ALLOWED_TEMPLATE_PACK = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# Auth redirects
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
