"""
Django settings for auditoria_aylupita project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import sys
from pathlib import Path

import dj_database_url
import environ

# runtime_paths vive en la raíz del proyecto (junto a manage.py), no dentro
# del paquete auditoria_aylupita — hace falta en sys.path explícitamente
# porque, empaquetado con PyInstaller, el mecanismo normal de import de
# Django (vía manage.py) no interviene.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from runtime_paths import carpeta_codigo, carpeta_escribible, esta_empaquetado  # noqa: E402

# BASE_DIR: carpeta de solo lectura con el código, templates y estáticos.
# Sin empaquetar es la raíz del proyecto de siempre; empaquetada con
# PyInstaller es la carpeta del bundle (sys._MEIPASS) — nunca la carpeta
# real donde vive el .exe, que puede no ser escribible.
BASE_DIR = carpeta_codigo()

# BASE_DIR_ESCRIBIBLE: carpeta donde SÍ se puede crear o modificar archivos
# (base de datos, media). Sin empaquetar es la misma que BASE_DIR;
# empaquetada, es la carpeta donde vive el .exe real — la única que el
# usuario controla y que persiste entre ejecuciones.
BASE_DIR_ESCRIBIBLE = carpeta_escribible()

# .env vive junto al .exe real (o en la raíz del proyecto en desarrollo,
# donde BASE_DIR_ESCRIBIBLE == BASE_DIR) — nunca dentro del bundle de solo
# lectura, y nunca se sube a git (confirmar en .gitignore). Si no existe
# (ej. una máquina sin Postgres configurado todavía), read_env() no hace
# nada y simplemente se usan las variables de entorno del sistema, si las
# hay — de ahí cae al fallback de SQLite más abajo.
env = environ.Env()
_RUTA_ENV = BASE_DIR_ESCRIBIBLE / ".env"
# encoding="utf-8-sig" (prompt 33): el Bloc de notas de Windows —y varios
# editores más— guardan en UTF-8 CON BOM. django-environ lee por defecto
# como "utf8", así que el BOM queda pegado al inicio de la PRIMERA línea:
# "﻿DATABASE_URL=..." ya no hace match con su expresión regular, la
# descarta como "Invalid line" y esa variable simplemente no existe.
# Comprobado: con un .env de dos líneas guardado con BOM, DATABASE_URL
# queda en None y DEBUG (segunda línea) se lee bien — o sea que la app
# arranca "sin configuración de nube" aunque el archivo esté ahí y se vea
# perfecto al abrirlo. "utf-8-sig" quita el BOM si existe y no cambia
# nada si no existe.
environ.Env.read_env(str(_RUTA_ENV), encoding="utf-8-sig")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1s^p=s9_-%a%6il%+%_3e_gjtd1_j_+06ebyqs^ou7pan&#_!i'

# SECURITY WARNING: don't run with debug turned on in production!
# Se lee de .env (prompt 22) — False por defecto si no está definida, así
# que una máquina sin .env configurado (ej. el .exe entregado al auditor)
# nunca corre con DEBUG=True por accidente. Actívalo explícitamente solo
# en tu propio .env de desarrollo local: DEBUG=True
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'inventario',
]

MIDDLEWARE = [
    # Primero en la lista a propósito (prompt 24): así envuelve TODO lo
    # demás y mide el tiempo real de extremo a extremo de la request, no
    # solo el de la vista — ver inventario/tiempos.py.
    'inventario.tiempos.TiempoRequestMiddleware',
    # Red de seguridad global de errores de conexión (prompt 19b, punto
    # 4): atrapa RequiereConexionError y cualquier OperationalError/
    # InterfaceError de CUALQUIER vista — incluida /admin/ y cualquier
    # vista futura — y muestra la pantalla amigable en vez de la página
    # técnica de Django. Va arriba para envolver a todo lo de abajo.
    'inventario.resiliencia.ManejoGlobalErrorConexionMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # AuthenticationMiddleware normal de Django (prompt 19b): ya no hace
    # falta reemplazarlo como en el prompt 19. El respaldo offline vive
    # ahora donde de verdad corresponde — en el backend de autenticación
    # (inventario.offline.BackendConRespaldoOffline, ver
    # AUTHENTICATION_BACKENDS más abajo), que es quien resuelve al
    # usuario — y la sesión ya no toca la base (SESSION_ENGINE).
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # Después de MessageMiddleware a propósito: necesita poder dejar un
    # mensaje para el usuario (ver ContinuidadSesionOfflineMiddleware en
    # inventario/offline.py).
    'inventario.offline.ContinuidadSesionOfflineMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Logging (prompt 24): sin esto, un logger.info() no imprime nada por
# default (el root logger de Python solo deja pasar WARNING o más grave) —
# se necesita este bloque explícito para que TiempoRequestMiddleware se
# vea en la consola/log del servidor.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'detallado': {
            'format': '%(asctime)s [%(levelname)s] %(threadName)s %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'detallado',
        },
        # Log a ARCHIVO, junto al ejecutable (prompt 33). Es la única
        # forma de tener rastro en el .exe de Windows: con console=False
        # el proceso no tiene consola, sys.stdout y sys.stderr son None,
        # y todo lo que va a la consola se descarta en silencio.
        #
        # Tiene que estar declarado AQUÍ, dentro de LOGGING, y no
        # agregarse a mano en tiempo de ejecución: get_wsgi_application()
        # vuelve a llamar a django.setup(), que re-aplica esta
        # configuración con dictConfig y borra cualquier handler añadido
        # por fuera. Ese fue justo el bug que hacía que el archivo solo
        # tuviera las líneas del arranque y ninguna request — y que me
        # llevó a concluir, mal, que la app no estaba sirviendo páginas.
        #
        # delay=True: no se toca el disco hasta que haya algo que
        # escribir, así que un directorio sin permiso de escritura no
        # impide arrancar.
        'archivo': {
            'class': 'logging.FileHandler',
            'filename': str(BASE_DIR_ESCRIBIBLE / 'diagnostico.log'),
            'encoding': 'utf-8',
            'delay': True,
            'formatter': 'detallado',
        },
    },
    'loggers': {
        # Un solo logger padre: "inventario.tiempos",
        # "inventario.offline" y "inventario.diagnostico" propagan aquí
        # por herencia. Antes cada uno se declaraba por separado con
        # propagate=False, que es justo lo que impedía sumarles un
        # handler común.
        'inventario': {
            'handlers': ['console', 'archivo'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

ROOT_URLCONF = 'auditoria_aylupita.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'inventario.context_processors.rol',
                'inventario.context_processors.pendientes_sincronizar',
                'inventario.context_processors.configuracion_bd',
            ],
        },
    },
]

WSGI_APPLICATION = 'auditoria_aylupita.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Postgres en la nube (Neon) si hay DATABASE_URL en el entorno/.env;
# si no, SQLite local como respaldo de desarrollo (prompt 18) — así se
# puede seguir probando sin nube si hace falta, sin tocar código.
#
# manage.py migrate usa DIRECT_DATABASE_URL en vez de DATABASE_URL cuando
# está definida: Neon recomienda la conexión directa (sin el pooler
# pgbouncer) específicamente para migraciones, mientras que la app en uso
# normal sí debe pasar por el pooler. Nota: app_desktop.py también corre
# "migrate" en cada arranque (self-healing en un equipo nuevo, prompt 13b)
# pero NO pasa por manage.py — ese arranque usa DATABASE_URL (el pooler)
# igual que el resto de la app. En la práctica un migrate sin nada
# pendiente es una operación liviana que no debería toparse con las
# limitaciones del pooler, pero si algún día da problemas ahí, es el
# lugar a revisar.
_es_comando_migrate = len(sys.argv) > 1 and sys.argv[1] == "migrate"

_database_url = env("DATABASE_URL", default=None)
_direct_database_url = env("DIRECT_DATABASE_URL", default=None)

if _database_url:
    _url_para_conectar = _direct_database_url if (_es_comando_migrate and _direct_database_url) else _database_url
    DATABASES = {
        "default": dj_database_url.parse(_url_para_conectar, conn_max_age=60, ssl_require=True)
    }
    # Detecta una conexión persistente muerta (ej. el cómputo serverless de
    # Neon se suspendió por inactividad) y la reabre en vez de fallar la
    # siguiente request — dj_database_url.parse() no siempre expone este
    # parámetro según la versión instalada, se fija aparte por seguridad.
    DATABASES["default"]["CONN_HEALTH_CHECKS"] = True

    # DISABLE_SERVER_SIDE_CURSORS (prompt 24): confirmado con evidencia real,
    # no por sospecha — bajo carga concurrente contra el pooler de Neon
    # (PgBouncer en modo transacción), una query que Django decide iterar
    # con cursor server-side ("DECLARE ... CURSOR ... WITH HOLD") puede
    # terminar con el DECLARE en una conexión de backend y el FETCH
    # posterior en OTRA (PgBouncer reasigna la conexión de backend entre
    # transacciones, de forma transparente e invisible para Django) —
    # reproducido en este mismo prompt: django.db.utils.ProgrammingError:
    # portal "_django_curs_..." does not exist, disparado por 6 requests
    # POST simultáneos. Un cursor server-side depende de que la MISMA
    # conexión de backend siga viva entre el DECLARE y el FETCH — algo que
    # el modo transacción de PgBouncer no garantiza. Esto es justo lo que
    # la documentación de Django recomienda desactivar cuando se usa un
    # pooler en modo transacción (no tiene relación con CONN_MAX_AGE: pasa
    # igual con conexiones nuevas en cada request, ver el diagnóstico del
    # prompt 24). Sin este cursor, Django trae los resultados de una vez
    # en la respuesta normal de la consulta — más simple y sin este riesgo,
    # al costo de no poder transmitir un queryset gigante en streaming
    # (irrelevante para el volumen de datos real de esta app).
    DATABASES["default"]["DISABLE_SERVER_SIDE_CURSORS"] = True

    # Timeouts explícitos (prompt 33) — SIN esto, cada intento de conexión
    # espera el timeout por defecto del sistema operativo. Medido: un
    # puerto cerrado en localhost rechaza en 0.00s (así se probó todo el
    # modo offline hasta el prompt 30, y por eso "funcionaba"), pero un
    # corte de red REAL descarta los paquetes en silencio y entonces la
    # espera es de 75 SEGUNDOS por intento. Con waitress en 4 hilos y el
    # dashboard consultando /estado-sincronizacion/ cada 4s, eso deja la
    # app entera sin responder en menos de 20 segundos.
    #
    # - connect_timeout: corta el intento de conexión NUEVA. 10s es
    #   holgado para que Neon despierte su cómputo serverless suspendido
    #   sin cortar una conexión legítima, y aun así ~7x más rápido que
    #   los 75s del sistema operativo.
    # - keepalives*: detectan una conexión YA ESTABLECIDA que murió (el
    #   caso "la app estaba abierta y se cayó la red"). Sin esto, un
    #   SELECT sobre un socket muerto espera el timeout de retransmisión
    #   de TCP, que son MINUTOS. Con esta configuración se detecta en
    #   ~30 + 3x10 = 60s como máximo, y normalmente mucho antes.
    #   Se usa keepalives (portable: Windows/macOS/Linux) y no
    #   tcp_user_timeout, que solo existe en Linux.
    DATABASES["default"].setdefault("OPTIONS", {}).update({
        "connect_timeout": 10,
        "keepalives": 1,
        "keepalives_idle": 30,
        "keepalives_interval": 10,
        "keepalives_count": 3,
    })

    # La configuración de la nube sí se pudo leer.
    BD_NUBE_NO_CONFIGURADA = False
elif esta_empaquetado():
    # Build empaquetado (.exe) SIN configuración de nube legible — falta
    # el .env junto al ejecutable, o su DATABASE_URL es inválida.
    #
    # ESTE ES EL BUG RAÍZ DEL PROMPT 33, confirmado con el log de la VM de
    # Windows: antes se caía en silencio al SQLite local de abajo, y eso
    # rompía TODO el motor offline de una forma muy difícil de ver. Con
    # SQLite como base "default", hay_conexion() devuelve True SIEMPRE (un
    # archivo local siempre "conecta", medido en 1ms), así que el motor
    # offline nunca se entera de que no hay nube y jamás se activa: el
    # login se valida contra una base vacía, y cada movimiento se encola y
    # se DESENCOLA de inmediato porque la escritura al SQLite local sí
    # tiene éxito (ver ColaOfflineMixin.form_valid). Resultado: todo se
    # guardaba en un db.sqlite3 huérfano que nunca sincronizaba con nada.
    #
    # Se deja a propósito una configuración de Postgres con un host
    # centinela inalcanzable, NO SQLite: así cualquier consulta falla como
    # un corte de conexión normal y el motor offline (cola local, caché de
    # credenciales, catálogo cacheado) funciona exactamente igual que ante
    # una caída de internet — que es justo la filosofía del resto del
    # motor: perder la base es un estado normal y esperado, no un motivo
    # para negarle la entrada a nadie.
    #
    # BD_NUBE_NO_CONFIGURADA distingue este caso de un corte de red común:
    # esto NO se arregla reconectándose a internet, hace falta que alguien
    # coloque el .env. La interfaz muestra un mensaje distinto por eso
    # (ver context_processors.py y templates/base.html).
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "no_configurada",
            "HOST": "base-de-datos-no-configurada.invalid",
            "USER": "",
            "PASSWORD": "",
            "PORT": "",
            "OPTIONS": {"connect_timeout": 2},
        }
    }
    BD_NUBE_NO_CONFIGURADA = True
else:
    # Desarrollo sin .env (nunca un .exe): SQLite local de siempre, para
    # poder trabajar sin tener Postgres configurado. Aquí sí es un
    # fallback legítimo — no hay ningún usuario final de por medio que
    # pueda quedarse trabajando contra una base huérfana sin darse cuenta.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR_ESCRIBIBLE / 'db.sqlite3',
        }
    }
    BD_NUBE_NO_CONFIGURADA = False

# "local_disco" (prompt 19, motor de sincronización offline): alias
# EXCLUSIVAMENTE local, nunca habla con Neon — ver inventario/db_router.py
# para qué modelos pueden vivir ahí (Producto/Categoria cacheados, más
# PendienteSincronizacion/CredencialOfflineCache). Es un archivo, así que
# sobrevive a un reinicio o un apagón. Existe siempre, haya o no conexión
# a Neon configurada, porque su propósito es precisamente seguir
# funcionando cuando "default" no responde.
#
# Prompt 19b, punto 3: antes había un segundo alias "local_memoria"
# (SQLite en RAM) para que la cola del vendedor se perdiera al cerrar la
# app. Esa decisión se revirtió explícitamente — los TRES roles usan
# ahora este mismo archivo y su cola sobrevive a un cierre forzado.
DATABASES["local_disco"] = {
    "ENGINE": "django.db.backends.sqlite3",
    "NAME": BASE_DIR_ESCRIBIBLE / "offline_local.sqlite3",
}

DATABASE_ROUTERS = ["inventario.db_router.OfflineRouter"]


# Sesiones en ARCHIVO, no en la base de datos (prompt 19b, punto 1).
#
# El backend por defecto de Django (django.contrib.sessions.backends.db)
# consulta la tabla django_session EN CADA REQUEST — confirmado al
# revisar el punto 1 de este prompt. Con ese backend, un usuario que ya
# había iniciado sesión con conexión perdía la sesión en cuanto se caía
# internet a media jornada, no solo al reiniciar: cada request moría
# antes de llegar a cualquier vista, así que la cola offline nunca
# llegaba siquiera a aplicarse.
#
# El backend de archivo no toca la base nunca, y a diferencia de
# "signed_cookies" no manda los datos de sesión dentro de la cookie ni
# pierde la posibilidad de invalidar una sesión del lado del servidor.
# Las sesiones viven junto a la base local, en la carpeta escribible.
SESSION_ENGINE = "django.contrib.sessions.backends.file"
SESSION_FILE_PATH = str(BASE_DIR_ESCRIBIBLE / "sesiones")
Path(SESSION_FILE_PATH).mkdir(parents=True, exist_ok=True)

# Backend de autenticación con respaldo offline (prompt 19b, punto 1):
# se comporta igual que el ModelBackend de Django mientras haya conexión
# (misma validación contra Neon) y solo cae a la caché local de
# credenciales cuando la base no responde — es lo que permite iniciar
# sesión durante un apagón y mantener viva una sesión ya iniciada.
AUTHENTICATION_BACKENDS = ["inventario.offline.BackendConRespaldoOffline"]


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-ni'  # Django no incluye es-gt; es-ni usa la misma convención numérica (punto decimal, coma de miles) que Guatemala

TIME_ZONE = 'America/Guatemala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media: no hay ningún FileField/ImageField en el catálogo actual, pero se
# deja definido (relativo a la carpeta escribible, no al bundle) para que
# cualquier subida de archivo que se agregue a futuro caiga en el lugar
# correcto sin tener que recordar este mismo problema de rutas.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR_ESCRIBIBLE / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/6.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# django-crispy-forms
CRISPY_ALLOWED_TEMPLATE_PACK = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"


# Auth redirects
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
