# Generated by Django 6.1 on 2026-08-25 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='producto_base',
            field=models.ForeignKey(blank=True, help_text='Si este producto es un paquete (ej. cubetazo), el producto individual que contiene.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes', to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_por_paquete',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de unidades del producto_base que contiene este paquete.', null=True),
        ),
    ]
