# Generated by Django 6.1 on 2026-08-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_producto_base_producto_unidades_por_paquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientosalida',
            name='cantidad',
            field=models.IntegerField(help_text='Para venta/merma siempre positivo. Para ajuste: positivo si el conteo físico encontró un faltante (resta stock), negativo si encontró un sobrante (suma stock) — ver generar_ajuste().'),
        ),
    ]
