# Generated by Django 6.1 on 2026-08-26 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_movimientosalida_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='unidades_por_paquete',
        ),
        migrations.AddField(
            model_name='producto',
            name='factor_equivalencia',
            field=models.PositiveIntegerField(default=1, help_text='Unidades de producto_base que consume vender 1 unidad de este producto.'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_base',
            field=models.ForeignKey(blank=True, help_text='Si este producto es una variante de precio o un paquete (ej. cubetazo) de otro, el producto base real.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derivados', to='inventario.producto'),
        ),
    ]
