# Generated by Django 6.1 on 2026-08-26 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_equivalencia_producto_derivado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreccionHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(max_length=30)),
                ('registro_id', models.PositiveIntegerField()),
                ('accion', models.CharField(choices=[('edicion', 'Edición'), ('eliminacion', 'Eliminación')], max_length=15)),
                ('datos_anteriores', models.JSONField()),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Correcciones al historial',
                'ordering': ['-fecha'],
            },
        ),
    ]
