# Generated by Django 6.1 on 2026-08-26 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_correccion_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteofisico',
            name='ajuste_generado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.movimientosalida'),
        ),
    ]
