# Generated by Django 6.1 on 2026-08-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_offline_sync_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialOfflineCache',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('user_id', models.PositiveIntegerField(db_index=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('aviso_password_cambiada', models.BooleanField(default=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.DeleteModel(
            name='SesionOfflineCache',
        ),
    ]
