# Generated by Django 6.1 on 2026-08-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_offline_credenciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoHistorialCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(max_length=30)),
                ('registro_id', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('producto_id', models.PositiveIntegerField(db_index=True)),
                ('payload', models.JSONField()),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_teorico_cache',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
