# Generated by Django 6.1 on 2026-09-01 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_historial_cache_y_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conteofisico',
            name='ocurrido_en',
            field=models.DateTimeField(db_index=True, help_text='Momento real en que se creó el registro en el equipo de quien lo registró. Para algo registrado sin conexión es la hora local de ese momento, NO la de sincronización.', null=True),
        ),
        migrations.AddField(
            model_name='conteofisico',
            name='reloj_sospechoso',
            field=models.BooleanField(default=False, help_text='El equipo que registró esto tenía el reloj adelantado respecto al servidor. El orden temporal de este registro puede no ser confiable.'),
        ),
        migrations.AddField(
            model_name='lotecompra',
            name='ocurrido_en',
            field=models.DateTimeField(db_index=True, help_text='Momento real en que se creó el registro en el equipo de quien lo registró. Para algo registrado sin conexión es la hora local de ese momento, NO la de sincronización.', null=True),
        ),
        migrations.AddField(
            model_name='lotecompra',
            name='reloj_sospechoso',
            field=models.BooleanField(default=False, help_text='El equipo que registró esto tenía el reloj adelantado respecto al servidor. El orden temporal de este registro puede no ser confiable.'),
        ),
        migrations.AddField(
            model_name='movimientosalida',
            name='ocurrido_en',
            field=models.DateTimeField(db_index=True, help_text='Momento real en que se creó el registro en el equipo de quien lo registró. Para algo registrado sin conexión es la hora local de ese momento, NO la de sincronización.', null=True),
        ),
        migrations.AddField(
            model_name='movimientosalida',
            name='reloj_sospechoso',
            field=models.BooleanField(default=False, help_text='El equipo que registró esto tenía el reloj adelantado respecto al servidor. El orden temporal de este registro puede no ser confiable.'),
        ),
        migrations.CreateModel(
            name='DiscrepanciaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contado', models.PositiveIntegerField()),
                ('teorico_al_conteo', models.IntegerField(help_text='Stock teórico en el instante exacto del conteo. Congelado: no cambia nunca.')),
                ('diferencia', models.IntegerField(help_text='contado − teorico_al_conteo. Congelado. Positivo = sobrante, negativo = faltante.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('resuelta', 'Resuelta con ajuste'), ('descartada', 'Revisada sin ajuste')], db_index=True, default='pendiente', max_length=12)),
                ('requiere_revision', models.BooleanField(default=False)),
                ('teorico_recalculado', models.IntegerField(blank=True, null=True)),
                ('diferencia_recalculada', models.IntegerField(blank=True, null=True)),
                ('motivo_revision', models.TextField(blank=True, default='')),
                ('cantidad_confirmada', models.IntegerField(blank=True, help_text='Lo que la persona decidió ajustar. Puede diferir de lo que sugirió el sistema.', null=True)),
                ('nota_resolucion', models.TextField(blank=True, default='')),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ajuste', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancia_origen', to='inventario.movimientosalida')),
                ('conteo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancia', to='inventario.conteofisico')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancias', to='inventario.producto')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'discrepancia de inventario',
                'verbose_name_plural': 'discrepancias de inventario',
                'ordering': ['-conteo__fecha', '-conteo__ocurrido_en'],
            },
        ),
    ]
