# Generated by Django 6.1 on 2026-09-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_backfill_ocurrido_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteofisico',
            name='ocurrido_en',
            field=models.DateTimeField(db_index=True, help_text='Momento real en que se creó el registro en el equipo de quien lo registró. Para algo registrado sin conexión es la hora local de ese momento, NO la de sincronización.'),
        ),
        migrations.AlterField(
            model_name='lotecompra',
            name='ocurrido_en',
            field=models.DateTimeField(db_index=True, help_text='Momento real en que se creó el registro en el equipo de quien lo registró. Para algo registrado sin conexión es la hora local de ese momento, NO la de sincronización.'),
        ),
        migrations.AlterField(
            model_name='movimientosalida',
            name='ocurrido_en',
            field=models.DateTimeField(db_index=True, help_text='Momento real en que se creó el registro en el equipo de quien lo registró. Para algo registrado sin conexión es la hora local de ese momento, NO la de sincronización.'),
        ),
    ]
