# Generated by Django 6.1 on 2026-09-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_ocurrido_en_obligatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correccionhistorial',
            name='accion',
            field=models.CharField(choices=[('edicion', 'Edición'), ('eliminacion', 'Eliminación'), ('nota', 'Nota automática')], max_length=15),
        ),
    ]
